---
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  - pytz=2023.3
  - python-dateutil=2.8.2
  - pip:
      - rpaframework==27.7.0
      - robocorp==1.2.4
      - robocorp-browser==2.2.1