channels:
  - conda-forge
dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pandas=1.5.2
  - pytz=2023.3
  - requests
  - pip:
    - rpaframework==27.7.0        # https://rpaframework.org/releasenotes.html
    - robocorp==1.2.4             # https://pypi.org/project/robocorp
    - robocorp-browser==2.2.1     # https://pypi.org/project/robocorp-browser
