name:
robocorp_rpa
channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - tesseract=4.1.1
  - nodejs=16.14.2
  - pip=22.1.2
  - pandas=1.5.2
  - pytz
  - wget
  - pip:
    - robotframework-browser==17.2.0
    - rpaframework==24.1.2
    - rpaframework-aws==5.2.8
    - rpaframework-google==7.0.3
    - rpaframework-recognition==5.1.2
rccPostInstall:
  - rfbrowser init
